### ISSUE TITLE
PHP Warning:  Undefined array key 314 in phar:///home/runner/work/cockpit/cockpit/tools/composer-require-checker/vendor/nikic/php-parser/lib/PhpParser/Lexer.php on line 293

### ISSUE THREAD

**Issue by OskarStark** [maglnet/ComposerRequireChecker#234]
I have an error using `ComposerRequireChecker 2.1.0@0c66698d487fcb5c66cf07108e2180c818fb2e72`, when running it with PHP 8. Not sure this is already fixed but it is not released.

Anything else I can provide to support you?

```
ComposerRequireChecker 2.1.0@0c66698d487fcb5c66cf07108e2180c818fb2e72
PHP Warning:  Undefined array key 314 in phar:///home/runner/work/cockpit/cockpit/tools/composer-require-checker/vendor/nikic/php-parser/lib/PhpParser/Lexer.php on line 293
PHP Fatal error:  Uncaught TypeError: PhpParser\Lexer::getNextToken(): Return value must be of type int, null returned in phar:///home/runner/work/cockpit/cockpit/tools/composer-require-checker/vendor/nikic/php-parser/lib/PhpParser/Lexer.php:327
Stack trace:
#0 phar:///home/runner/work/cockpit/cockpit/tools/composer-require-checker/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(208): PhpParser\Lexer->getNextToken()
#1 phar:///home/runner/work/cockpit/cockpit/tools/composer-require-checker/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(158): PhpParser\ParserAbstract->doParse()
#2 phar:///home/runner/work/cockpit/cockpit/tools/composer-require-checker/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(51): PhpParser\ParserAbstract->parse()
#3 phar:///home/runner/work/cockpit/cockpit/tools/composer-require-checker/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(32): PhpParser\Parser\Multiple->tryParse()
#4 phar:///home/runner/work/cockpit/cockpit/tools/composer-require-checker/src/ComposerRequireChecker/ASTLocator/LocateASTFromFiles.php(35): PhpParser\Parser\Multiple->parse()
#5 phar:///home/runner/work/cockpit/cockpit/tools/composer-require-checker/src/ComposerRequireChecker/DefinedSymbolsLocator/LocateDefinedSymbolsFromASTRoots.php(27): ComposerRequireChecker\ASTLocator\LocateASTFromFiles->__invoke()
#6 phar:///home/runner/work/cockpit/cockpit/tools/composer-require-checker/src/ComposerRequireChecker/Cli/CheckCommand.php(78): ComposerRequireChecker\DefinedSymbolsLocator\LocateDefinedSymbolsFromASTRoots->__invoke()
#7 phar:///home/runner/work/cockpit/cockpit/tools/composer-require-checker/vendor/symfony/console/Command/Command.php(255): ComposerRequireChecker\Cli\CheckCommand->execute()
#8 phar:///home/runner/work/cockpit/cockpit/tools/composer-require-checker/vendor/symfony/console/Application.php(924): Symfony\Component\Console\Command\Command->run()
#9 phar:///home/runner/work/cockpit/cockpit/tools/composer-require-checker/vendor/symfony/console/Application.php(265): Symfony\Component\Console\Application->doRunCommand()
#10 phar:///home/runner/work/cockpit/cockpit/tools/composer-require-checker/vendor/symfony/console/Application.php(141): Symfony\Component\Console\Application->doRun()
#11 phar:///home/runner/work/cockpit/cockpit/tools/composer-require-checker/bin/composer-require-checker.php(32): Symfony\Component\Console\Application->run()
#12 /home/runner/work/cockpit/cockpit/tools/composer-require-checker(10): include('...')
#13 {main}
  thrown in phar:///home/runner/work/cockpit/cockpit/tools/composer-require-checker/vendor/nikic/php-parser/lib/PhpParser/Lexer.php on line 327
Error: Process completed with exit code 255.
```

composer.json
```json
{
    "name": "foo/bar",
    "type": "project",
    "description": "foo",
    "license": "proprietary",
    "require": {
        "php": "^8.0",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "ext-pdo_pgsql": "*",
        "composer/package-versions-deprecated": "1.11.99.1",
        "doctrine/annotations": "^1.0",
        "doctrine/doctrine-bundle": "^2.2",
        "doctrine/doctrine-migrations-bundle": "^3.0",
        "doctrine/orm": "^2.8",
        "ergebnis/clock": "^2.2",
        "phpdocumentor/reflection-docblock": "^5.2",
        "psr/log": "^1.1",
        "sensio/framework-extra-bundle": "^5.1",
        "symfony/asset": "5.2.*",
        "symfony/console": "5.2.*",
        "symfony/dependency-injection": "5.2.*",
        "symfony/dotenv": "5.2.*",
        "symfony/expression-language": "5.2.*",
        "symfony/flex": "^1.3.1",
        "symfony/form": "5.2.*",
        "symfony/framework-bundle": "5.2.*",
        "symfony/http-client": "5.2.*",
        "symfony/http-kernel": "5.2.*",
        "symfony/intl": "5.2.*",
        "symfony/mailer": "5.2.*",
        "symfony/mime": "5.2.*",
        "symfony/monolog-bundle": "^3.1",
        "symfony/notifier": "5.2.*",
        "symfony/process": "5.2.*",
        "symfony/property-access": "5.2.*",
        "symfony/property-info": "5.2.*",
        "symfony/proxy-manager-bridge": "5.2.*",
        "symfony/routing": "5.2.*",
        "symfony/security-bundle": "5.2.*",
        "symfony/serializer": "5.2.*",
        "symfony/string": "5.2.*",
        "symfony/translation": "5.2.*",
        "symfony/twig-bundle": "5.2.*",
        "symfony/validator": "5.2.*",
        "symfony/web-link": "5.2.*",
        "symfony/yaml": "5.2.*",
        "thecodingmachine/safe": "^1.3",
        "twig/extra-bundle": "^3.2",
        "twig/twig": "^3.2",
        "webmozart/assert": "^1.9"
    },
    "replace": {
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php72": "*"
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "require-dev": {
        "dama/doctrine-test-bundle": "^6.3",
        "ergebnis/composer-normalize": "^2.3",
        "ergebnis/factory-bot": "^0.4.0",
        "ergebnis/test-util": "^1.4",
        "phpstan/extension-installer": "^1.1",
        "phpstan/phpstan": "^0.12.64",
        "phpstan/phpstan-deprecation-rules": "^0.12.6",
        "phpstan/phpstan-doctrine": "^0.12.26",
        "phpstan/phpstan-phpunit": "^0.12.17",
        "phpstan/phpstan-strict-rules": "^0.12.7",
        "phpstan/phpstan-symfony": "^0.12.12",
        "phpstan/phpstan-webmozart-assert": "^0.12.8",
        "phpunit/phpunit": "^9.5",
        "symfony/browser-kit": "5.2.*",
        "symfony/css-selector": "5.2.*",
        "symfony/debug-bundle": "5.2.*",
        "symfony/maker-bundle": "^1.0",
        "symfony/phpunit-bridge": "5.2.*",
        "symfony/stopwatch": "5.2.*",
        "symfony/var-dumper": "5.2.*",
        "symfony/web-profiler-bundle": "5.2.*",
        "thecodingmachine/phpstan-safe-rule": "^1.0"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "5.2.*"
        },
        "unused": [
            "ext-ctype",
            "ext-iconv",
            "ext-pdo_pgsql",
            "symfony/flex",
            "symfony/proxy-manager-bridge",
            "thecodingmachine/safe"
        ]
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ],
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        }
    }
}

```

cc @localheinz

**Comment by Ocramius** [comment]
PHP 8 support is not yet here: please run on PHP 7 for now.

**Comment by localheinz** [comment]
Also see #201.

**Comment by OskarStark** [comment]
Didn't know, thanks
